aws_access_key    = " "
aws_secret_key    = " "
aws_region      = "us-east-1"
s3-bucket-lambda-code = "non-resized-image"
s3-bucket-dest    = "resized-images"
sns-name       = "Resized-Image-SNS-Topic"
mail-id       = "indrabhushan.maluche@gmail.com"
